name: pull
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  pull_from_registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull internal image
        run: docker pull ghcr.io/wechorg/fromgithubtoken:6
      - name: list docker images
        run: docker image ls
